image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - sed -i "s/TF_TOKEN/$TEAMTOKEN/g" main.tf
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate -var-file=provider.tfvars

plan:
  stage: plan
  script:
    - terraform plan -out "planfile" -var-file=provider.tfvars
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
    - terraform output
  dependencies:
    - plan
  #when: manual%